### ISSUE TITLE
Source for Postalcode Data

### ISSUE THREAD

**Issue by kevinkreiser** [whosonfirst-data/whosonfirst-data-postalcode-ch#1]
Browsing around this repo it seemed that all the `geojson` i could find was rendered at `null island`. I like Switzerland so I thought I'd have a search around for a datasource. If this isn't needed and I just couldnt find the right place for the shape data in the repo then please ignore the rest of what I'm going to say..

So like any self respecting european govt the Swiss put lots of data up for free. In fact you can get shapefiles containing the polygons and associated postal codes for Switzerland here http://www.cadastre.ch/internet/kataster/de/home/services/service/plz.html

First the license is found within a zip file here http://data.geo.admin.ch/ch.swisstopo-vd.ortschaftenverzeichnis_plz/

The license is in German so I'll do my best to translate the relevant "Copyright" part:

> The information contained on the federal website are made accessible to the public. No legal rights are transferred to you by downloading or copying the contents, images, photographs or other files contained herein.
> 
> The copyright and all other rights to contents, images, photographs or other files on the federal website are owned outright by the federal government or by specifically named parties. Written agreement must be obtained in advance for the reproduction of any elements.

Anyway after that you can get the shapefiles here: http://data.geo.admin.ch/ch.swisstopo-vd.ortschaftenverzeichnis_plz/PLZO_GDB_LV95.zip

The  shape layer you want which has the associated postal code is in `PLZO_PLZ.shp` the column with the postal code in it is named `PLZ`

**Comment by thisisaaronland** [comment]
Awesome! I will see about importing this in the next day or two. Whoosh!!

**Comment by kevinkreiser** [comment]
Woohoo! Let me know if I can help in any way!

**Comment by thisisaaronland** [comment]
![screen shot 2016-05-04 at 14 47 48](https://cloud.githubusercontent.com/assets/12658759/15030681/9da050f6-1208-11e6-8b20-25255f53b0e6.png)
![screen shot 2016-05-04 at 14 54 09](https://cloud.githubusercontent.com/assets/12658759/15030682/9da29ff0-1208-11e6-96e7-432f18a7d883.png)
